// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef __linux__

#include "xstatus.h"
#include "xparameters.h"
#include "xhuffman.h"

extern XHuffman_Config XHuffman_ConfigTable[];

XHuffman_Config *XHuffman_LookupConfig(u16 DeviceId) {
	XHuffman_Config *ConfigPtr = NULL;

	int Index;

	for (Index = 0; Index < XPAR_XHUFFMAN_NUM_INSTANCES; Index++) {
		if (XHuffman_ConfigTable[Index].DeviceId == DeviceId) {
			ConfigPtr = &XHuffman_ConfigTable[Index];
			break;
		}
	}

	return ConfigPtr;
}

int XHuffman_Initialize(XHuffman *InstancePtr, u16 DeviceId) {
	XHuffman_Config *ConfigPtr;

	Xil_AssertNonvoid(InstancePtr != NULL);

	ConfigPtr = XHuffman_LookupConfig(DeviceId);
	if (ConfigPtr == NULL) {
		InstancePtr->IsReady = 0;
		return (XST_DEVICE_NOT_FOUND);
	}

	return XHuffman_CfgInitialize(InstancePtr, ConfigPtr);
}

#endif

