// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.1
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

// AXILiteS
// 0x00000 : Control signals
//           bit 0  - ap_start (Read/Write/COH)
//           bit 1  - ap_done (Read/COR)
//           bit 2  - ap_idle (Read)
//           bit 3  - ap_ready (Read)
//           bit 7  - auto_restart (Read/Write)
//           others - reserved
// 0x00004 : Global Interrupt Enable Register
//           bit 0  - Global Interrupt Enable (Read/Write)
//           others - reserved
// 0x00008 : IP Interrupt Enable Register (Read/Write)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0x0000c : IP Interrupt Status Register (Read/TOW)
//           bit 0  - Channel 0 (ap_done)
//           bit 1  - Channel 1 (ap_ready)
//           others - reserved
// 0xc0000 : Data signal of in_size
//           bit 31~0 - in_size[31:0] (Read/Write)
// 0xc0004 : reserved
// 0xc0008 : Data signal of out_size
//           bit 31~0 - out_size[31:0] (Read)
// 0xc000c : Control signal of out_size
//           bit 0  - out_size_ap_vld (Read/COR)
//           others - reserved
// 0x40000 ~
// 0x7ffff : Memory 'compressed' (37500 * 8b)
//           Word n : bit [ 7: 0] - compressed[4n]
//                    bit [15: 8] - compressed[4n+1]
//                    bit [23:16] - compressed[4n+2]
//                    bit [31:24] - compressed[4n+3]
// 0x80000 ~
// 0xbffff : Memory 'decompressed' (37500 * 8b)
//           Word n : bit [ 7: 0] - decompressed[4n]
//                    bit [15: 8] - decompressed[4n+1]
//                    bit [23:16] - decompressed[4n+2]
//                    bit [31:24] - decompressed[4n+3]
// (SC = Self Clear, COR = Clear on Read, TOW = Toggle on Write, COH = Clear on Handshake)

#define XDECOMPRESS_AXILITES_ADDR_AP_CTRL           0x00000
#define XDECOMPRESS_AXILITES_ADDR_GIE               0x00004
#define XDECOMPRESS_AXILITES_ADDR_IER               0x00008
#define XDECOMPRESS_AXILITES_ADDR_ISR               0x0000c
#define XDECOMPRESS_AXILITES_ADDR_IN_SIZE_DATA      0xc0000
#define XDECOMPRESS_AXILITES_BITS_IN_SIZE_DATA      32
#define XDECOMPRESS_AXILITES_ADDR_OUT_SIZE_DATA     0xc0008
#define XDECOMPRESS_AXILITES_BITS_OUT_SIZE_DATA     32
#define XDECOMPRESS_AXILITES_ADDR_OUT_SIZE_CTRL     0xc000c
#define XDECOMPRESS_AXILITES_ADDR_COMPRESSED_BASE   0x40000
#define XDECOMPRESS_AXILITES_ADDR_COMPRESSED_HIGH   0x7ffff
#define XDECOMPRESS_AXILITES_WIDTH_COMPRESSED       8
#define XDECOMPRESS_AXILITES_DEPTH_COMPRESSED       37500
#define XDECOMPRESS_AXILITES_ADDR_DECOMPRESSED_BASE 0x80000
#define XDECOMPRESS_AXILITES_ADDR_DECOMPRESSED_HIGH 0xbffff
#define XDECOMPRESS_AXILITES_WIDTH_DECOMPRESSED     8
#define XDECOMPRESS_AXILITES_DEPTH_DECOMPRESSED     37500

